server:
  port: 8887
  error:
    path: /error
github:
  client-id: 763e0aa92a6f3229f4b1
  client-secret: 11417871c2cc2ef4b82da05c25dd9df4ae9460f9
  client-redirect-uri: http://localhost:8887/callback
  authorize-uri: https://github.com/login/oauth/authorize
  access-token-api: https://github.com/login/oauth/access_token
  user-api: https://api.github.com/user
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/charles_community?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: charles
    password: Charles@415
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: @activeProfile@ #来自maven profile中配置的springboot激活的profile
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: cc.charles.community.model
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    cc:
      charles:
        community:
          mapper: debug
    root: info
  file: /data/java_service/log/charles-community/community.log
  file.max-size: 200MB
  file.max-history: 3
custom-setting:
  upload-path-dir: /Users/charlesdong/Projects/Java/staticFile/upload/
  suffix-limit:
    - .jpg
    - .jpeg
    - .png
    - .gif