package cc.charles.community.model;

import org.springframework.stereotype.Component;

@Component
public class Comment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.ID
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.CONTENT
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.PARENT_ID
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.TYPE
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.GMT_CREATE
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.GMT_MODIFIED
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.OBSERVER
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    private Integer observer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.COMMENT_COUNT
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    private Integer commentCount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.ID
     *
     * @return the value of comment.ID
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.ID
     *
     * @param id the value for comment.ID
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.CONTENT
     *
     * @return the value of comment.CONTENT
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.CONTENT
     *
     * @param content the value for comment.CONTENT
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.PARENT_ID
     *
     * @return the value of comment.PARENT_ID
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.PARENT_ID
     *
     * @param parentId the value for comment.PARENT_ID
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.TYPE
     *
     * @return the value of comment.TYPE
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.TYPE
     *
     * @param type the value for comment.TYPE
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.GMT_CREATE
     *
     * @return the value of comment.GMT_CREATE
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.GMT_CREATE
     *
     * @param gmtCreate the value for comment.GMT_CREATE
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.GMT_MODIFIED
     *
     * @return the value of comment.GMT_MODIFIED
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.GMT_MODIFIED
     *
     * @param gmtModified the value for comment.GMT_MODIFIED
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.OBSERVER
     *
     * @return the value of comment.OBSERVER
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public Integer getObserver() {
        return observer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.OBSERVER
     *
     * @param observer the value for comment.OBSERVER
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public void setObserver(Integer observer) {
        this.observer = observer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.COMMENT_COUNT
     *
     * @return the value of comment.COMMENT_COUNT
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public Integer getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.COMMENT_COUNT
     *
     * @param commentCount the value for comment.COMMENT_COUNT
     *
     * @mbg.generated Sat Jul 11 20:38:33 CST 2020
     */
    public void setCommentCount(Integer commentCount) {
        this.commentCount = commentCount;
    }
}